### PR TITLE
[project] bump for Xyce 7.4

### PR DESCRIPTION
**Pull request by sjkelly**
Depends on: https://github.com/JuliaPackaging/Yggdrasil/pull/3930

### CODE REVIEW

**Comment by pepijndevos** [comment]
Seems there is a missing dll on windows?
```
 ERROR: LoadError: LoadError: InitError: could not load library "C:\Users\runneradmin\.julia\artifacts\cabf27aa69e9590e7c187e52fb98fba1d9b6841d\bin\libbelos.dll"
A dynamic link library (DLL) initialization routine failed. 
```

**Comment by sjkelly** [comment]
That shouldn't be happening. That DLL is from Trilinos. Maybe it also needs a bump?

**Comment by pepijndevos** [comment]
Maybe

**Comment by Keno** [comment]
Trilinos stopped working on 1.6.3. Not sure what the issue is, but I filed as https://github.com/JuliaPackaging/Yggdrasil/issues/3971. In the meantime, I'll force CI here to 1.6.2, which should let us move forward.

**Comment by giordano** [comment]
Can someone on Windows try to use [`DependencyWalker.jl`](https://github.com/giordano/DependencyWalker.jl) to debug the issue?

**Comment by Keno** [comment]
It's not a dependency issue - I just posted the crashing function over in the Yggdrasil issue. Let's discuss there, since it's not Xyce related.

**Pull request merged**
